//! Tiny control service (127.0.0.1, random port) — the sidecar's push channel
//! into the shell. Endpoints (all require `Authorization: Bearer <token>`):
//!
//!   POST /ping            — sidecar heartbeat (anti-orphan liveness)
//!   POST /update-install  — {path}: spawn installer detached, then exit
//!   POST /show-window     — {kind, html, width, height}: show a dialog window
//!   POST /close-window    — {kind}: close a dialog window
//!   POST /restart-app     — relaunch the shell
//!
//! tiny_http is used rather than axum: four fixed endpoints, blocking IO on a
//! plain thread, no extra dependency weight for a first Tauri build.

use serde::Deserialize;
use std::process::{Command, Stdio};
use tauri::{AppHandle, Manager};

use std::sync::Arc;

use crate::sidecar::{SidecarState, StatusKind};

#[derive(Deserialize)]
struct UpdateInstallBody {
    path: String,
}

/// Heartbeat body: the sidecar reports the control API port it actually
/// bound, so the shell can track it even if the reserved port shifted.
#[derive(Deserialize)]
struct PingBody {
    #[serde(rename = "controlPort")]
    control_port: u16,
}

#[derive(Deserialize)]
struct ShowWindowBody {
    kind: String,
    width: u32,
    height: u32,
    #[serde(default = "default_true")]
    dark: bool,
}

#[derive(Deserialize)]
struct CloseWindowBody {
    kind: String,
}

fn default_true() -> bool {
    true
}

/// Start the control server on a random 127.0.0.1 port; returns the bound port.
/// The token is generated by the caller and handed to the sidecar via env.
pub fn start(app: AppHandle, token: String) -> u16 {
    let server = match tiny_http::Server::http("127.0.0.1:0") {
        Ok(s) => s,
        Err(e) => {
            log::error!("ctl_server: failed to bind: {e}");
            return 0;
        }
    };
    let port = match server.server_addr().to_ip() {
        Some(addr) => addr.port(),
        None => {
            log::error!("ctl_server: address not an IP");
            return 0;
        }
    };

    std::thread::spawn(move || {
        for mut request in server.incoming_requests() {
            let authorized = request
                .headers()
                .iter()
                .find(|h| h.field.as_str().as_str().eq_ignore_ascii_case("authorization"))
                .map(|h| h.value.as_str().trim().to_string())
                .map(|v| v == format!("Bearer {token}"))
                .unwrap_or(false);

            if !authorized {
                let _ = request.respond(
                    tiny_http::Response::from_string("unauthorized")
                        .with_status_code(401),
                );
                continue;
            }

            let url = request.url().to_string();
            let method = request.method().clone();

            let mut body = String::new();
            if method == tiny_http::Method::Post {
                // Read up to 1MB (take() needs Sized; the reader is a trait
                // object, so read manually with a cap).
                let mut buf = [0u8; 8192];
                let mut total = 0usize;
                let mut reader = request.as_reader();
                loop {
                    match std::io::Read::read(&mut reader, &mut buf) {
                        Ok(0) => break,
                        Ok(n) => {
                            total += n;
                            if total > (1 << 20) {
                                break;
                            }
                            body.push_str(&String::from_utf8_lossy(&buf[..n]));
                        }
                        Err(_) => break,
                    }
                }
            }

            let response = handle(&app, &url, &body);
            let _ = request.respond(response);
        }
    });

    log::info!("ctl_server: listening on 127.0.0.1:{port}");
    port
}

fn handle(app: &AppHandle, url: &str, body: &str) -> tiny_http::Response<std::io::Cursor<Vec<u8>>> {
    let ok = |text: &str| {
        tiny_http::Response::from_string(text.to_string())
            .with_status_code(200)
    };

    let (path, _query) = url.split_once('?').unwrap_or((url, ""));

    match path {
        "/ping" => {
            // Keep the shell's view of the control API port in sync: the
            // sidecar may have re-bound elsewhere (reserved-port race).
            if let Ok(b) = serde_json::from_str::<PingBody>(body) {
                if b.control_port != 0 {
                    let state = app.state::<Arc<SidecarState>>();
                    state.sidecar_api_port.store(b.control_port, std::sync::atomic::Ordering::SeqCst);
                }
            }
            ok("pong")
        }
        "/update-install" => {
            match serde_json::from_str::<UpdateInstallBody>(body) {
                Ok(b) => {
                    let result = spawn_detached_installer(&b.path);
                    match result {
                        Ok(_) => {
                            log::info!("ctl_server: installer spawned, exiting");
                            app.exit(0);
                            ok("installer spawned")
                        }
                        Err(e) => {
                            log::error!("ctl_server: spawn installer failed: {e}");
                            tiny_http::Response::from_string(format!("spawn failed: {e}"))
                                .with_status_code(500)
                        }
                    }
                }
                Err(e) => {
                    tiny_http::Response::from_string(format!("bad body: {e}"))
                        .with_status_code(400)
                }
            }
        }
        "/show-window" => {
            match serde_json::from_str::<ShowWindowBody>(body) {
                Ok(b) => {
                    log::info!("ctl_server: /show-window kind={} {}x{}", b.kind, b.width, b.height);
                    let app2 = app.clone();
                    let _ = app.run_on_main_thread(move || {
                        // HTML lives in the sidecar's control server
                        // (/updater/page cache); the window loads it by URL.
                        let result = crate::windows::show_dialog_window(
                            &app2,
                            &b.kind,
                            b.width,
                            b.height,
                            b.dark,
                        );
                        if let Err(e) = result {
                            log::error!("ctl_server: show_dialog_window({}) failed: {e}", b.kind);
                        }
                    });
                    ok("window shown")
                }
                Err(e) => {
                    tiny_http::Response::from_string(format!("bad body: {e}"))
                        .with_status_code(400)
                }
            }
        }
        "/close-window" => {
            match serde_json::from_str::<CloseWindowBody>(body) {
                Ok(b) => {
                    log::info!("ctl_server: /close-window kind={}", b.kind);
                    let app2 = app.clone();
                    let _ = app.run_on_main_thread(move || {
                        crate::windows::close_dialog_window(&app2, &b.kind);
                    });
                    ok("window closed")
                }
                Err(e) => {
                    tiny_http::Response::from_string(format!("bad body: {e}"))
                        .with_status_code(400)
                }
            }
        }
        "/restart-app" => {
            let exe = std::env::current_exe();
            match exe {
                Ok(exe) => {
                    // Kill the sidecar first so the relaunched shell owns a fresh one.
                    let state = app.state::<Arc<SidecarState>>();
                    let snapshot = crate::sidecar::take_snapshot(&state);
                    if snapshot.kind != StatusKind::Stopped {
                        let handle = app.clone();
                        tauri::async_runtime::spawn(async move {
                            let _ = crate::sidecar::shutdown(&handle).await;
                        });
                    }
                    let _ = Command::new(exe).spawn();
                    app.exit(0);
                    ok("restarting")
                }
                Err(e) => {
                    tiny_http::Response::from_string(format!("no exe: {e}"))
                        .with_status_code(500)
                }
            }
        }
        _ => tiny_http::Response::from_string("not found").with_status_code(404),
    }
}

/// Spawn the installer fully detached from the shell's process tree, so the
/// shell's own exit / taskkill cleanup cannot take it down mid-install.
#[cfg(windows)]
fn spawn_detached_installer(path: &str) -> std::io::Result<()> {
    use std::os::windows::process::CommandExt;

    const CREATE_NEW_PROCESS_GROUP: u32 = 0x0000_0200;
    const DETACHED_PROCESS: u32 = 0x0000_0008;

    Command::new(path)
        .arg("--updated")
        .creation_flags(CREATE_NEW_PROCESS_GROUP | DETACHED_PROCESS)
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .spawn()?;
    Ok(())
}

#[cfg(not(windows))]
fn spawn_detached_installer(path: &str) -> std::io::Result<()> {
    Command::new(path)
        .arg("--updated")
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .spawn()?;
    Ok(())
}
