fn main() {
    // Declare the shell's compat_* commands so tauri-build autogenerates
    // `allow-<command>` / `deny-<command>` app permissions
    // (permissions/autogenerated). Without an app ACL the remote-origin
    // WebUI page (http://127.0.0.1:3080) cannot invoke any of them —
    // Tauri 2 rejects custom commands from remote origins unless a
    // capability grants them explicitly ("无法连接 GitHub" root cause).
    let attrs = tauri_build::Attributes::new().app_manifest(
        tauri_build::AppManifest::default().commands(&[
            "compat_get_app_version",
            "compat_get_platform",
            "compat_get_server_status",
            "compat_get_control_info",
            "compat_quit_app",
            "compat_restart_service",
            "compat_window_minimize",
            "compat_window_maximize",
            "compat_window_is_maximized",
            "compat_window_close",
            "compat_toggle_devtools",
            "compat_open_data_dir",
            "compat_open_config_file",
            "compat_get_auto_start",
            "compat_set_auto_start",
            "compat_save_file_from_url",
            "compat_save_local_file",
            "compat_open_gateway_chooser",
            "compat_reload_main_window",
        ]),
    );
    tauri_build::try_build(attrs).expect("tauri build script failed");
}
